@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQyNzk1NDU3LCJleHAiOjE2NDI3OTkwNTd9.YLZwiwn4GXPxszVUX7lZaWFieAj7eq8iiah6W6WM_8A
GET  http://localhost:9000/v1/ HTTP/1.1
###
POST http://localhost:9000/v1/user/login HTTP/1.1
content-type: application/json

{
  "email": "admin@email.com",
  "password": "testing123"
}
###
POST http://localhost:9000/v1/user/registrasi HTTP/1.1
content-type: application/json

{
  "email": "admin2@email.com",
  "password": "Testing123@"
}
###
POST http://localhost:9000/v1/pasien HTTP/1.1
content-type: application/json

{
  "name": "fahira",
  "bird_of_date": "2003-06-14",
  "address": "medan"
}
###
GET http://localhost:9000/v1/pasien HTTP/1.1
content-type: application/json
###
GET http://localhost:9000/v1/dokter/visitors HTTP/1.1
content-type: application/json
Authorization: {{token}}
###
GET http://localhost:9000/v1/dokter HTTP/1.1
content-type: application/json
###
GET http://localhost:9000/v1/users HTTP/1.1
content-type: application/json
###
GET http://localhost:9000/v1/visitors HTTP/1.1
content-type: application/json
###
GET http://localhost:9000/v1/dokter/visitor/1 HTTP/1.1
content-type: application/json
Authorization: {{token}}

###
POST http://localhost:9000/v1/visitor HTTP/1.1
content-type: application/json

{
  "pasien_id": 1,
  "dokter_id": 2,
  "chekup" : "greget"
}