version: "3.9"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=danang
      - MYSQL_USER=danang
      - MYSQL_PASSWORD=danang
      - MYSQL_DATABASE=default
    # volumes: 
    #   - /data_mysql:/var/lib/mysql
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "9001:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT=3306
    container_name: phpmyadmin-app
  # express:
  #   depends_on: 
  #     - mysql
  #   build: .
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_HOST=mysql-app
  #     - MYSQL_USER=root
  #     - MYSQL_PASS=root
  #     - MYSQL_DB=default
  #   volumes:
  #     - ./express-files:/app/public/images
  #   ports:
  #     - "9000:9000"
  #   container_name: express-app
networks:
  backend: